services:
  server:
    build: .
    container_name: sensor_server
    ports:
      - "8007:8000"
      - "5007:5000"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
    command: ["sh", "-c", "python server.py & python api.py"]