version: "3.8"
services:
  server:
    build: .
    container_name: sensor_server
    ports:
      - "8000:8000"
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
